Add 'validatePaymentInstrument' Method To Stripe Payment Class
compucorp/com.drastikbydesign.stripe pull request #6
Opened 2019-01-30 04:15 UTC by vinuvarshith

## Overview
New versions of webform_civicrm doesnt work with Stripe payment. It asks for 'credit card number' and 'cvv' number even if both are given.

## Technical details
Previously there was 'Stripe' related code inside webform_civicrm that handled this (Stripe doesnt need 'card number' and 'cvv number' as it has 'stripe token' generated using card details.
Now 'Stripe' related logic are removed from webform_civicrm and it is expected that Stripe extension would handle this using 'validatePaymentInstrument' method in its Payment class.
This PR add this method and after this Stripe payments work without the above issue using new webform_civicrm.

2019-01-30 16:22 UTC, igorpavlov-zz requested changes

2019-01-30 16:22 UTC, igorpavlov commented on CRM/Core/Payment/Stripe.php
> +   * Stripe payment instrument validation.
Let's make the description imperative: "Validates Stripe payment instrument"
Also, if you could provide a link to the payment instrument like that:
`@see https://stripe.com/some-documentation-page` that would be great for devs.

2019-01-30 16:22 UTC, igorpavlov commented on CRM/Core/Payment/Stripe.php
> +    // set credit_card_number and cvv2 as not required as we have stripe_token
Let me suggest a potentially better comment:
`// We do not require neither credit_card_number nor cvv2 because we use stripe_token`

2019-01-30 16:22 UTC, igorpavlov commented on CRM/Core/Payment/Stripe.php
> +    CRM_Core_Form::validateMandatoryFields($mandatoryFields, $values, $errors);
Please add an empty line above.

2019-01-30 16:22 UTC, igorpavlov commented on CRM/Core/Payment/Stripe.php
> +    if (empty($_POST['stripe_token'])) {
I guess if token is not passed there is no need to perform other validations? So would it be better to exec this check earlier in the function and return?

```php
if (empty($_POST['stripe_token'])) {
  $errors['stripe_token'] = ts('Stripe token not found.');
  
  return;
}

$mandatoryFields = $this->getMandatoryFields();
// and the rest of code...
```

Also, it seems a bit weird that we are accessing $_POST inside this func, isn't token passed inside `$values`? Just checking.

2019-01-30 18:23 UTC, vinuvarshith commented
@igorpavlov Thanks for the review and for pointing out that we are using $_POST variable values directly. This was done like this in webform_civicrm and I kind of borrowed the same code. Now I have improved the implementation using respective methods. Can you please review again?

2019-01-31 10:15 UTC, igorpavlov-zz approved these changes

2019-01-31 12:23 UTC, merged